version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: orm_db
      MYSQL_ROOT_PASSWORD: ormdb
    ports:
      - 3306:3306
    volumes:
      - ./.mysqldata:/var/lib/mysql