name: orm_teste
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  orm: ^3.4.3
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.21.0
  hard_analyser: ^1.1.0
  http: ^1.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

